/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Covan(props) {
    const { nodes, materials } = useGLTF('../../public/medias/Covan.glb')
  return (
    <group {...props} dispose={null}>
      <group
        position={[10.744, 8.223, -22.295]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[8.137, 0.116, 8.657]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={materials['Fabric Square Patterrn']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_1.geometry}
          material={materials['Dark Brown Leather']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_2.geometry}
          material={materials['Plastic brown material']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_3.geometry}
          material={materials['Scratched Transparent Plastic']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_4.geometry}
          material={materials['pollen logo']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_5.geometry}
          material={materials['Black Plastic']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_6.geometry}
          material={materials['Light iron']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_7.geometry}
          material={materials.Gold}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_8.geometry}
          material={materials['Grained red plastic']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('../../public/medias/Covan.glb')