/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Hive(props) {
    const { nodes, materials } = useGLTF('../../public/medias/Hive.glb')
  return (
    <group {...props} dispose={null}>
      <group
        position={[9.518, 5.023, 0.977]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[4.79, 0.068, 5.096]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials['Fabric Square Patterrn.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_1.geometry}
          material={materials['Gold.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_2.geometry}
          material={materials['Grained red plastic.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_3.geometry}
          material={materials['Gold.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_4.geometry}
          material={materials['Black Plastic']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_5.geometry}
          material={materials['Light iron.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_6.geometry}
          material={materials['pollen logo.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_7.geometry}
          material={materials['Scratched Transparent Plastic.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_8.geometry}
          material={materials['Dark Brown Leather.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_9.geometry}
          material={materials['Plastic brown material.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('../../public/medias/Hive.glb')