/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export function HoneyComb(props) {
  const { nodes, materials } = useGLTF('../../public/medias/HoneyComb.glb')
  return (
    <group {...props} dispose={null}>
      <group
        position={[10.875, 6.792, -51.598]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.042}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front_1.geometry}
          material={materials['Fabric Square Patterrn']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front_2.geometry}
          material={materials['Dark Brown Leather']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front_3.geometry}
          material={materials['Plastic brown material']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front_4.geometry}
          material={materials['Scratched Transparent Plastic']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front_5.geometry}
          material={materials['Black Plastic']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front_6.geometry}
          material={materials['Light iron']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front_7.geometry}
          material={materials['Brown matte metal']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front_8.geometry}
          material={materials['Grained red plastic']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front_9.geometry}
          material={materials['pollen logo.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front_10.geometry}
          material={materials.Gold}
        />
      </group>
    </group>
  )
}

useGLTF.preload('../../public/medias/HoneyComb.glb')