/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Swarm(props) {
  const { nodes, materials } = useGLTF('../../public/medias/Swarm.glb')
  return (
    <group {...props} dispose={null}>
      <group
        position={[9.585, 4.424, -73.185]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.028}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front001_1.geometry}
          material={materials['Fabric Square Patterrn.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front001_2.geometry}
          material={materials['Black Plastic']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front001_3.geometry}
          material={materials['Light iron.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front001_4.geometry}
          material={materials['pollen logo.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front001_5.geometry}
          material={materials['Plastic brown material.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front001_6.geometry}
          material={materials['Brown matte metal.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front001_7.geometry}
          material={materials['Grained red plastic.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front001_8.geometry}
          material={materials['Dark Brown Leather.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front001_9.geometry}
          material={materials['Scratched Transparent Plastic.002']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.front001_10.geometry}
          material={materials['Gold.003']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('../../public/medias/Swarm.glb')